// Specialties and their sub-classifications. Everything here is easy to edit.
export const SPECIALTIES = [
  "General Practice / Family Medicine",
  "Obstetrics & Gynaecology",
  "ENT (Otolaryngology)",
  "General Surgery",
  "Plastic & Reconstructive Surgery",
  "Internal Medicine",
  "Paediatrics",
  "Orthopaedics",
  "Ophthalmology",
  "Urology",
  "Dermatology",
  "Psychiatry",
  "Anaesthesia & Critical Care",
  "Emergency Medicine",
  "Radiology",
  "Pathology",
  "Oncology",
  "Neurosurgery",
  "Oral & Maxillofacial Surgery",
  "Dental Surgery",
  "Other",
];

export const CATEGORIES = {
  "General Practice / Family Medicine": ["Acute & emergency", "Chronic disease", "Infectious disease (HIV/TB/malaria)", "Maternal & child health", "Minor procedures", "Mental health", "Preventive & screening", "Other"],
  "Obstetrics & Gynaecology": ["Obstetric emergency", "Labour & delivery", "Antenatal care", "Benign gynaecology", "Gynae-oncology", "Urogynaecology", "Fertility & reproductive", "Family planning", "Other"],
  "ENT (Otolaryngology)": ["Emergencies", "Otology", "Rhinology", "Head & neck", "Laryngology", "Facial plastics", "Paediatric ENT", "Other"],
  "General Surgery": ["Trauma & emergency", "Hepatobiliary", "Upper GI", "Colorectal", "Breast & endocrine", "Hernia", "Soft tissue", "Other"],
  "Plastic & Reconstructive Surgery": ["Reconstructive", "Aesthetic / cosmetic", "Burns", "Hand & peripheral nerve", "Craniofacial", "Cleft lip & palate", "Skin & soft tissue / skin cancer", "Microsurgery & free flaps", "Trauma", "Lower limb & pressure sores", "Other"],
  "Internal Medicine": ["General internal medicine", "Cardiology", "Respiratory", "Gastroenterology", "Nephrology", "Neurology", "Endocrinology", "Infectious disease", "Haematology", "Medical oncology", "Rheumatology", "Dermatology", "Geriatrics", "Critical care", "Palliative care", "Other"],
  "Paediatrics": ["Neonatology", "Paediatric emergency", "Infectious disease", "Respiratory", "Nutrition", "Cardiology", "Neurology", "Other"],
  "Orthopaedics": ["Trauma & fractures", "Spine", "Arthroplasty", "Sports & soft tissue", "Paediatric", "Hand", "Oncology", "Other"],
  "Ophthalmology": ["Cataract & lens", "Glaucoma", "Cornea & external eye", "Retina & vitreous", "Oculoplastics", "Paediatric & strabismus", "Emergency & trauma", "Other"],
  "Urology": ["Stones & endourology", "Uro-oncology", "Andrology", "Reconstructive", "Paediatric", "Emergency", "Other"],
  "Dermatology": ["Inflammatory", "Infections", "Skin cancer", "Paediatric", "STI", "Other"],
  "Psychiatry": ["Mood disorders", "Psychosis", "Substance use", "Child & adolescent", "Anxiety & trauma", "Other"],
  "Anaesthesia & Critical Care": ["General anaesthesia", "Regional", "Obstetric", "Critical care / ICU", "Paediatric", "Cardiac", "Neuroanaesthesia", "Trauma & resuscitation", "Day surgery", "Pain", "Other"],
  "Emergency Medicine": ["Trauma", "Medical emergency", "Toxicology", "Resuscitation", "Paediatric emergency", "Other"],
  "Radiology": ["Diagnostic", "Interventional", "Ultrasound", "CT", "MRI", "Other"],
  "Pathology": ["Histopathology", "Cytology", "Haematology", "Microbiology", "Chemical pathology", "Other"],
  "Oncology": ["Medical oncology", "Radiation oncology", "Surgical oncology", "Palliative care", "Other"],
  "Neurosurgery": ["Neuro-trauma / head injury", "Spine & spinal cord", "Neuro-oncology (brain & spine tumours)", "Vascular (aneurysm / AVM)", "Hydrocephalus & CSF disorders", "Functional & epilepsy", "Skull base", "Peripheral nerve", "Paediatric neurosurgery", "Neurosurgical emergency", "Other"],
  "Oral & Maxillofacial Surgery": ["Maxillofacial trauma", "Dentoalveolar (extractions & impactions)", "Head & neck oncology (oral cancer)", "Orthognathic (jaw correction)", "Temporomandibular joint (TMJ)", "Cleft lip & palate", "Salivary gland", "Maxillofacial infection", "Reconstruction & deformity", "Implantology", "Other"],
  "Dental Surgery": ["Restorative / operative", "Endodontics (root canal)", "Periodontics (gums)", "Prosthodontics (crowns, bridges, dentures)", "Orthodontics", "Paediatric dentistry", "Oral medicine & pathology", "Exodontia / minor oral surgery", "Dental & maxillofacial radiology", "Preventive & community", "Other"],
  "Other": ["General", "Other"],
};

export const INVOLVEMENT = [
  "Observed",
  "Assisted",
  "Performed under supervision",
  "Performed independently",
  "Lead clinician / managed",
];

export const PROCEDURE_ROLES = [
  "Observed",
  "Assisted",
  "Performed under supervision",
  "Performed independently",
];

export const COMPETENCY_ROLES = [
  "Performed under supervision",
  "Performed independently",
];

export const PROCEDURE_TARGETS = [
  { specialty: "Core", name: "Suturing", target: 10 },
  { specialty: "Core", name: "Incision and drainage", target: 5 },
  { specialty: "Core", name: "Wound debridement", target: 5 },
  { specialty: "Core", name: "Peripheral IV cannulation", target: 20 },
  { specialty: "General Surgery", name: "Appendicectomy", target: 5 },
  { specialty: "General Surgery", name: "Hernia repair", target: 5 },
  { specialty: "General Surgery", name: "Laparotomy", target: 3 },
  { specialty: "Obstetrics & Gynaecology", name: "Normal vaginal delivery", target: 20 },
  { specialty: "Obstetrics & Gynaecology", name: "Caesarean section", target: 10 },
  { specialty: "Obstetrics & Gynaecology", name: "Perineal repair", target: 10 },
  { specialty: "Anaesthesia & Critical Care", name: "Endotracheal intubation", target: 20 },
  { specialty: "Anaesthesia & Critical Care", name: "Spinal anaesthesia", target: 20 },
  { specialty: "Anaesthesia & Critical Care", name: "Resuscitation leadership", target: 10 },
  { specialty: "Emergency Medicine", name: "Trauma primary survey", target: 20 },
  { specialty: "Emergency Medicine", name: "Chest drain insertion", target: 5 },
  { specialty: "Emergency Medicine", name: "Fracture reduction", target: 10 },
  { specialty: "Internal Medicine", name: "Lumbar puncture", target: 5 },
  { specialty: "Internal Medicine", name: "Pleural aspiration", target: 5 },
  { specialty: "Internal Medicine", name: "Ascitic tap", target: 10 },
  { specialty: "Paediatrics", name: "Neonatal resuscitation", target: 10 },
  { specialty: "Paediatrics", name: "Paediatric lumbar puncture", target: 5 },
  { specialty: "Orthopaedics", name: "Closed fracture reduction", target: 10 },
  { specialty: "Orthopaedics", name: "Plaster application", target: 20 },
  { specialty: "Orthopaedics", name: "Joint aspiration", target: 5 },
  { specialty: "Urology", name: "Urethral catheterisation", target: 20 },
  { specialty: "Urology", name: "Suprapubic catheterisation", target: 5 },
  { specialty: "ENT (Otolaryngology)", name: "Ear toilet", target: 10 },
  { specialty: "ENT (Otolaryngology)", name: "Nasal packing", target: 5 },
  { specialty: "Ophthalmology", name: "Slit lamp examination", target: 20 },
  { specialty: "Ophthalmology", name: "Foreign body removal", target: 5 },
  { specialty: "Dental Surgery", name: "Dental extraction", target: 20 },
  { specialty: "Oral & Maxillofacial Surgery", name: "Dentoalveolar extraction", target: 20 },
];
