-- ============================================================================
-- DEPRECATED - DO NOT RUN.
--
-- This file previously disabled Supabase email verification by confirming users
-- at the database level. Keep it inert so it is not run by mistake.
--
-- To stop future users from being auto-confirmed, run:
--   supabase/remove_auto_email_confirmation.sql
--
-- Historical auto-confirm logic, intentionally commented out:
--
-- update auth.users set email_confirmed_at = now()
-- where email_confirmed_at is null;
--
-- create or replace function public.auto_confirm_user()
-- returns trigger language plpgsql security definer as $$
-- begin
--   if new.email_confirmed_at is null then
--     new.email_confirmed_at := now();
--   end if;
--   return new;
-- end; $$;
--
-- drop trigger if exists auto_confirm_on_signup on auth.users;
-- create trigger auto_confirm_on_signup
--   before insert on auth.users
--   for each row execute function public.auto_confirm_user();
-- ============================================================================
